name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install and run Luacheck
      run: |
        sudo apt-get install luarocks
        luarocks install --local luacheck
        /home/runner/.luarocks/bin/luacheck . --no-color -q

    - name: Update Curseforge Translations
      run: ./cf_translations.sh
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}

    - name: Create Classic Package
      run: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        GITHUB_OAUTH: ${{ secrets.GITHUB_OAUTH }}
        WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}