name: CI

on:
  push:
    branches:
      - bcc
    tags:
      - '**-bcc**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install and run Luacheck
      uses: nebularg/actions-luacheck@v1
      with:
        args: "--no-color -q"

    - name: Update Curseforge Translations
      run: ./cf_translations.sh
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}

    - name: Create BCC Package
      uses: BigWigsMods/packager@master
      with:
        args: -g bcc -m .pkgmeta-bcc -w 25953 -n "{package-name}-{project-version}"
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
        WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
        WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}