name: CI

on:
  push:
    branches:
      - bc
    tags:
      - '**-bc**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install and run Luacheck
      uses: nebularg/actions-luacheck@v1
      with:
        args: "--no-color -q"

    - name: Update Curseforge Translations
      run: ./cf_translations.sh
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}

    - name: Create BC Package
      uses: BigWigsMods/packager@master
      with:
        args: -g bc -m .pkgmeta-bc
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
        WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}